package social

// Platform names
const (
	PlatformBlogger         = "blogger"
	PlatformBluesky         = "bluesky"
	PlatformDiaspora        = "diaspora"
	PlatformDiscord         = "discord"
	PlatformDouban          = "douban"
	PlatformEmail           = "email"
	PlatformEvernote        = "evernote"
	PlatformFacebook        = "facebook"
	PlatformFlipboard       = "flipboard"
	PlatformGitHub          = "github"
	PlatformGmail           = "gmail"
	PlatformGoogleBookmarks = "google.bookmarks"
	PlatformInstagram       = "instagram"
	PlatformInstapaper      = "instapaper"
	PlatformLineMe          = "line.me"
	PlatformLinkedIn        = "linkedin"
	PlatformLiveJournal     = "livejournal"
	PlatformHackerNews      = "hacker.news"
	PlatformMastodon        = "mastodon"
	PlatformMedium          = "medium"
	PlatformOkRu            = "ok.ru"
	PlatformPinterest       = "pinterest"
	PlatformPocket          = "getpocket"
	PlatformPrint           = "print"
	PlatformCopyLink        = "copylink"
	PlatformNativeShare     = "nativeshare"
	PlatformQZone           = "qzone"
	PlatformReddit          = "reddit"
	PlatformRenren          = "renren"
	PlatformSkype           = "skype"
	PlatformSMS             = "sms"
	PlatformSnapchat        = "snapchat"
	PlatformTelegram        = "telegram"
	PlatformTelegramMe      = "telegram.me"
	PlatformThreema         = "threema"
	PlatformThreads         = "threads"
	PlatformTikTok          = "tiktok"
	PlatformTumblr          = "tumblr"
	PlatformTwitter         = "twitter"
	PlatformVK              = "vk"
	PlatformWeibo           = "weibo"
	PlatformWhatsApp        = "whatsapp"
	PlatformXing            = "xing"
	PlatformYahoo           = "yahoo"
	PlatformYouTube         = "youtube"
)

// Submit URLs for social media platforms (for sharing)
const (
	SubmitURLBlogger         = "https://www.blogger.com/blog-this.g"
	SubmitURLBluesky         = "https://bsky.app/intent/compose"
	SubmitURLDiaspora        = "https://share.diasporafoundation.org/"
	SubmitURLDiscord         = "https://discord.com"
	SubmitURLDouban          = "http://www.douban.com/recommend/"
	SubmitURLEmail           = "mailto:"
	SubmitURLEvernote        = "https://www.evernote.com/clip.action"
	SubmitURLFacebook        = "https://www.facebook.com/sharer.php"
	SubmitURLFlipboard       = "https://share.flipboard.com/bookmarklet/popout"
	SubmitURLGitHub          = "https://github.com"
	SubmitURLGmail           = "https://mail.google.com/mail/"
	SubmitURLGoogleBookmarks = "https://www.google.com/bookmarks/mark"
	SubmitURLInstagram       = "https://www.instagram.com"
	SubmitURLInstapaper      = "http://www.instapaper.com/edit"
	SubmitURLLineMe          = "https://lineit.line.me/share/ui"
	SubmitURLLinkedIn        = "https://www.linkedin.com/sharing/share-offsite/"
	SubmitURLLiveJournal     = "http://www.livejournal.com/update.bml"
	SubmitURLHackerNews      = "https://news.ycombinator.com/submitlink"
	SubmitURLMastodon        = "https://mastodon.social/share"
	SubmitURLMedium          = "https://medium.com"
	SubmitURLOkRu            = "https://connect.ok.ru/dk"
	SubmitURLPinterest       = "https://pinterest.com/pin/create/button/"
	SubmitURLPocket          = "https://getpocket.com/save"
	SubmitURLQZone           = "http://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey"
	SubmitURLReddit          = "https://reddit.com/submit"
	SubmitURLRenren          = "http://widget.renren.com/dialog/share"
	SubmitURLSkype           = "https://web.skype.com/share"
	SubmitURLSMS             = "sms:"
	SubmitURLSnapchat        = "https://www.snapchat.com"
	SubmitURLTelegramMe      = "https://t.me/share/url"
	SubmitURLThreema         = "threema://compose"
	SubmitURLThreads         = "https://threads.net/intent/post"
	SubmitURLTikTok          = "https://www.tiktok.com"
	SubmitURLTumblr          = "https://www.tumblr.com/widgets/share/tool"
	SubmitURLTwitter         = "https://x.com/intent/tweet"
	SubmitURLVK              = "http://vk.com/share.php"
	SubmitURLWeibo           = "http://service.weibo.com/share/share.php"
	SubmitURLWhatsApp        = "https://api.whatsapp.com/send"
	SubmitURLXing            = "https://www.xing.com/spi/shares/new"
	SubmitURLYahoo           = "http://compose.mail.yahoo.com/"
	SubmitURLYouTube         = "https://www.youtube.com"
)

// Domain URLs for social media platforms (for linking)
const (
	DomainURLBlogger     = "https://www.blogger.com"
	DomainURLBluesky     = "https://bsky.app"
	DomainURLDiaspora    = "https://diasporafoundation.org"
	DomainURLDiscord     = "https://discord.com"
	DomainURLDouban      = "http://www.douban.com"
	DomainURLEvernote    = "https://www.evernote.com"
	DomainURLFacebook    = "https://www.facebook.com"
	DomainURLFlipboard   = "https://flipboard.com"
	DomainURLGitHub      = "https://github.com"
	DomainURLGmail       = "https://mail.google.com"
	DomainURLInstagram   = "https://www.instagram.com"
	DomainURLInstapaper  = "http://www.instapaper.com"
	DomainURLLineMe      = "https://line.me"
	DomainURLLinkedIn    = "https://www.linkedin.com"
	DomainURLLiveJournal = "http://www.livejournal.com"
	DomainURLHackerNews  = "https://news.ycombinator.com"
	DomainURLMastodon    = "https://mastodon.social"
	DomainURLMedium      = "https://medium.com"
	DomainURLOkRu        = "https://ok.ru"
	DomainURLPinterest   = "https://pinterest.com"
	DomainURLPocket      = "https://getpocket.com"
	DomainURLQZone       = "http://qzone.qq.com"
	DomainURLReddit      = "https://reddit.com"
	DomainURLRenren      = "http://renren.com"
	DomainURLSkype       = "https://skype.com"
	DomainURLSnapchat    = "https://www.snapchat.com"
	DomainURLTelegram    = "https://telegram.org"
	DomainURLThreema     = "https://threema.ch"
	DomainURLThreads     = "https://threads.net"
	DomainURLTikTok      = "https://www.tiktok.com"
	DomainURLTumblr      = "https://tumblr.com"
	DomainURLTwitter     = "https://x.com"
	DomainURLVK          = "https://vk.com"
	DomainURLWeibo       = "http://weibo.com"
	DomainURLWhatsApp    = "https://whatsapp.com"
	DomainURLXing        = "https://www.xing.com"
	DomainURLYahoo       = "https://yahoo.com"
	DomainURLYouTube     = "https://www.youtube.com"
)

// Font Awesome icon classes
const (
	FontAwesomeBlogger         = "fa-rss"
	FontAwesomeBluesky         = "fa-bluesky"
	FontAwesomeDiaspora        = "fa-share-alt"
	FontAwesomeDiscord         = "fa-discord"
	FontAwesomeDouban          = "fa-share"
	FontAwesomeEmail           = "fa-envelope"
	FontAwesomeEvernote        = "fa-sticky-note"
	FontAwesomeFacebook        = "fa-facebook-official"
	FontAwesomeFlipboard       = "fa-flipboard"
	FontAwesomeGitHub          = "fa-github"
	FontAwesomeGmail           = "fa-google"
	FontAwesomeGoogleBookmarks = "fa-bookmark"
	FontAwesomeInstagram       = "fa-instagram"
	FontAwesomeInstapaper      = "fa-instapaper"
	FontAwesomeLineMe          = "fa-line"
	FontAwesomeLinkedIn        = "fa-linkedin"
	FontAwesomeLiveJournal     = "fa-pencil"
	FontAwesomeHackerNews      = "fa-hacker-news"
	FontAwesomeMastodon        = "fa-mastodon"
	FontAwesomeMedium          = "fa-medium"
	FontAwesomeOkRu            = "fa-odnoklassniki"
	FontAwesomePinterest       = "fa-pinterest"
	FontAwesomePocket          = "fa-get-pocket"
	FontAwesomePrint           = "fa-print"
	FontAwesomeCopyLink        = "fa-link"
	FontAwesomeNativeShare     = "fa-share-nodes"
	FontAwesomeQZone           = "fa-qq"
	FontAwesomeReddit          = "fa-reddit"
	FontAwesomeRenren          = "fa-renren"
	FontAwesomeSkype           = "fa-skype"
	FontAwesomeSMS             = "fa-comment-sms"
	FontAwesomeSnapchat        = "fa-snapchat"
	FontAwesomeTelegramMe      = "fa-telegram"
	FontAwesomeThreema         = "fa-shield"
	FontAwesomeThreads         = "fa-threads"
	FontAwesomeTikTok          = "fa-tiktok"
	FontAwesomeTumblr          = "fa-tumblr"
	FontAwesomeTwitter         = "fa-twitter"
	FontAwesomeVK              = "fa-vk"
	FontAwesomeWeibo           = "fa-weibo"
	FontAwesomeWhatsApp        = "fa-whatsapp"
	FontAwesomeXing            = "fa-xing"
	FontAwesomeYahoo           = "fa-yahoo"
	FontAwesomeYouTube         = "fa-youtube"
)

// Bootstrap icon classes
const (
	BootstrapIconBlogger         = "bi-rss"
	BootstrapIconBluesky         = "bi-bluesky"
	BootstrapIconDiaspora        = "bi-share"
	BootstrapIconDiscord         = "bi-discord"
	BootstrapIconDouban          = "bi-share"
	BootstrapIconEmail           = "bi-envelope"
	BootstrapIconEvernote        = "bi-sticky"
	BootstrapIconFacebook        = "bi-facebook"
	BootstrapIconFlipboard       = "bi-flipboard"
	BootstrapIconGitHub          = "bi-github"
	BootstrapIconGmail           = "bi-google"
	BootstrapIconGoogleBookmarks = "bi-bookmark"
	BootstrapIconInstagram       = "bi-instagram"
	BootstrapIconInstapaper      = "bi-bookmark"
	BootstrapIconLineMe          = "bi-line"
	BootstrapIconLinkedIn        = "bi-linkedin"
	BootstrapIconLiveJournal     = "bi-pencil"
	BootstrapIconHackerNews      = "bi-hacker-news"
	BootstrapIconMastodon        = "bi-mastodon"
	BootstrapIconMedium          = "bi-medium"
	BootstrapIconOkRu            = "bi-person"
	BootstrapIconPinterest       = "bi-pinterest"
	BootstrapIconPocket          = "bi-bookmark"
	BootstrapIconPrint           = "bi-printer"
	BootstrapIconCopyLink        = "bi-link-45deg"
	BootstrapIconNativeShare     = "bi-share"
	BootstrapIconQZone           = "bi-qq"
	BootstrapIconReddit          = "bi-reddit"
	BootstrapIconRenren          = "bi-person"
	BootstrapIconSkype           = "bi-skype"
	BootstrapIconSMS             = "bi-chat-sms"
	BootstrapIconSnapchat        = "bi-snapchat"
	BootstrapIconTelegramMe      = "bi-telegram"
	BootstrapIconThreema         = "bi-shield"
	BootstrapIconThreads         = "bi-threads"
	BootstrapIconTikTok          = "bi-tiktok"
	BootstrapIconTumblr          = "bi-tumblr"
	BootstrapIconTwitter         = "bi-twitter"
	BootstrapIconVK              = "bi-vk"
	BootstrapIconWeibo           = "bi-weibo"
	BootstrapIconWhatsApp        = "bi-whatsapp"
	BootstrapIconXing            = "bi-xing"
	BootstrapIconYahoo           = "bi-yahoo"
	BootstrapIconYouTube         = "bi-youtube"
)

// Icon library types
const (
	IconLibraryFontAwesome = "fontawesome"
	IconLibraryBootstrap   = "bootstrap"
)

// Sort strategies for platform ordering
const (
	SortStrategyManual       = "manual"       // Use Platforms or PlatformOrder as specified (default)
	SortStrategyAlphabetical = "alphabetical" // Sort platforms alphabetically
	SortStrategyPopularity   = "popularity"   // Sort by popularity (most popular first)
)

// Platform colors (hex values from WPZoom reference)
const (
	ColorBluesky   = "#0285FF"
	ColorDiscord   = "#7289DA"
	ColorFacebook  = "#0866FF"
	ColorGitHub    = "#221E1B"
	ColorInstagram = "#E4405F"
	ColorLinkedIn  = "#0966C2"
	ColorMastodon  = "#6364FF"
	ColorMedium    = "#01AB6C"
	ColorPinterest = "#C92619"
	ColorReddit    = "#E74A1E"
	ColorSkype     = "#28ABE3"
	ColorSnapchat  = "#000000"
	ColorTelegram  = "#0088CC"
	ColorTikTok    = "#69C9D0"
	ColorThreads   = "#000000"
	ColorTwitter   = "#000000" // X/Twitter now uses black
	ColorWhatsApp  = "#25D366"
	ColorYouTube   = "#E02A20"
	ColorDefault   = "#333333" // For email, copy-link, print, etc.
)
